### ISSUE TITLE
Update element-resize-detector dependency

### ISSUE THREAD

**Issue by burkhartt** [d6u/resize-observer-lite#1]
The library element-resize-detector has some bug fixes, so a package update would fix some issues we are dealing with. Specifically this: https://github.com/wnr/element-resize-detector/issues/61

**Comment by burkhartt** [comment]
I was going to push a branch, but realized that I don't have permission to do so. The code block I updated was in package.json:
`
"dependencies": {
    "element-resize-detector": "1.1.11"
  },
`

**Comment by d6u** [comment]
Thanks for that heads up! I will update the tonight (PST). Are you seeing issue in https://github.com/d6u/react-container-query or just this repo?

**Comment by burkhartt** [comment]
We are using just this library. It probably shows up in the other as well then. Thanks!

Sent from my iPhone

On May 8, 2017, at 5:59 PM, Daiwei Lu <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for that heads up! I will update the tonight (PST). Are you seeing issue in https://github.com/d6u/react-container-query or just this repo?

**Comment by d6u** [comment]
Pushed 0.2.2 to npm.
